from pprint import pprint as pp
import requests
import json
import csv
import argparse

guidelines = """
INSTRUCTIONS

You will be presented with a transcript of a sales call between a seller/sales representative and a customer. The transcript can be noisy and contain several mistakes, e.g. when both speakers are speaking simultaneously. Only the raw transcript will be provided and not the Speaker IDs, so you will have to identify the seller and the customer in the conversation in order to perform your task.

Your job is to read the transcript carefully and answer a few questions regarding the prospect of the deal being discussed, e.g. customer sentiment, concrete next steps, mentions of competitors, or any blockers from closing the deal. Construct your response using only the information contained in the call transcript. If you are unable to find sufficient evidence to answer a given question, say so in the response rather than conjecturing beyond what’s evident from the call transcript.

Make sure your response is direct, concise and professional. Refrain from using redacted PIIs (e.g. [ORG-1], [PERSON-2]) in your response and use generic terms such as “seller”, “customer”, “seller’s product” and “customer’s boss” as much as possible. Only use the specific naming convention ([PERSON-1]) when there are other individuals mentioned apart from seller/customer that are worth noting. Avoid using pronouns in your response when possible. If you have to, use they/their/them.

For every question, a "seed" answer generated by a model will be provided to assist you. Only use the seed answer as a rough first draft. Add to or remove from it as you see fit.
"""
url = "https://xgenide.salesforceresearch.ai/api/upload"

def upload(input_data, queue_name, task_name):
    examples = []
    for id, transcript, questions, answers in input_data:
        inputs = [{
            "label": "",
            "type": "text",
            "content": f"{transcript}"
        }]
        outputs = []
        for question, answer in zip(questions, answers):
            outputs.append({
                "label": f"{question}",
                "type": "text",
                "content": f"{answer}"
            })

        id = id.split("_")
        id = "_".join(id[2:])
        # "#task_name": f"{id}",
        example = {
            "inputs": inputs,
            "outputs": outputs,
            "metadata": {
                "input_header": "",
                "output_headder": "questions",
                "task_name": f"{task_name}",
                "desc": f"{guidelines}",
                "queue_name": f"{queue_name}"
            },
        }
        examples.append(example)
    import ipdb; ipdb.set_trace()
    data = {'data': json.dumps(examples, separators=(',', ':'))}
    res = requests.post(url, json=data)
    print (res)
    return res

def main(args):
    calltype, length = [args.calltype], [args.length]
    if args.calltype is None:
        calltype = "voice video".split()
        length = "short medium long".split()
    for calltype_ in calltype:
        for length_ in length:
            input_data = []
            with open(f"/Users/jason.lee2/scr/xgen-ide/04_2024/10_data2/{calltype_}-{length_}.csv") as f:
                reader = csv.reader(f)
                for idx, row in enumerate(reader):
                    if args.maxlength == idx:
                        break
                    id = row[0]
                    transcript = row[1]
                    questions = row[2::2]
                    answers = row[3::2]
                    assert len(questions) == len(answers)
                    input_data.append(
                        (id, transcript, questions, answers)
                    )
            queue_name = f"gi_queue_0411_04"
            task_name = "gi_task_0411_04"
            upload(input_data, queue_name, task_name)
    print (1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--calltype", type=str, default=None)
    parser.add_argument("--length", type=str, default=None)
    parser.add_argument("--maxlength", type=int, default=-1)
    args = parser.parse_args()
    main(args)
