from pprint import pprint as pp
import requests
import json
import csv
import argparse

guidelines = """
INSTRUCTIONS

You will be presented with a transcript of a sales call between a seller/sales representative and a customer. The transcript can be noisy and contain several mistakes, e.g. when both speakers are speaking simultaneously. Only the raw transcript will be provided and not the Speaker IDs, so you will have to identify the seller and the customer in the conversation in order to perform your task.

Your job is to read the transcript carefully and answer a few questions regarding the prospect of the deal being discussed, e.g. customer sentiment, concrete next steps, mentions of competitors, or any blockers from closing the deal. Construct your response using only the information contained in the call transcript. If you are unable to find sufficient evidence to answer a given question, say so in the response rather than conjecturing beyond what’s evident from the call transcript.

Make sure your response is direct, concise and professional. Refrain from using redacted PIIs (e.g. [ORG-1], [PERSON-2]) in your response and use generic terms such as “seller”, “customer”, “seller’s product” and “customer’s boss” as much as possible. Only use the specific naming convention ([PERSON-1]) when there are other individuals mentioned apart from seller/customer that are worth noting. Avoid using pronouns in your response when possible. If you have to, use they/their/them.

For every question, a "seed" answer generated by a model will be provided to assist you. Only use the seed answer as a rough first draft. Add to or remove from it as you see fit.
"""
guidelines = ""
url = "https://xgenide.salesforceresearch.ai/api/upload"

bad_qs = [
    "Based on the transcript, how would you rate the salesperson's closing skills? Did they use a soft or hard close, and how did the buyer respond?",
    "Did the salesperson use persuasive techniques, such as urgency, scarcity, social proof, or authority, to encourage the potential buyer to make a decision?",
    "Can you provide examples of questions that facilitated the buyer's self-discovery process?",
    "What questions or suggestions should the Rep have asked based on the sales model, that were not asked as part of this call?",
    "How did the salesperson handle any silence or pauses in the conversation?",
]

def upload(input_data, queue_name, task_name):
    examples = []
    for id, transcript, questions, answers in input_data:
        inputs = [{
            "label": "",
            "type": "text",
            "content": f"{transcript}"
        }]
        outputs = []
        q_idx = 1
        for question, answer in zip(questions, answers):
            if question.strip() in bad_qs:
                continue

            outputs.append({
                "label": f"{q_idx}. {question}",
                "type": "text",
                "content": f"{answer}"
            })
            q_idx += 1

        id = id.split("_")
        id = "_".join(id[1:])
        # "#task_name": f"{id}",
        example = {
            "inputs": inputs,
            "outputs": outputs,
            "metadata": {
                "input_header": "Transcript",
                "output_headder": "Questions",
                "task_name": f"{task_name}",
                "desc": f"{guidelines}",
                "queue_name": f"{queue_name}",
                "id": f"{id}",
            },
        }
        examples.append(example)
    data = {'data': json.dumps(examples, separators=(',', ':'))}
    res = requests.post(url, json=data)
    print (f"requests.post result: {res}")
    return res

def main(args):
    queue_name = f"gi_backup_queue"
    queue_name = f"gi_main_queue_2"
    task_name = "gi_task"
    with open(f"/Users/jason.lee2/scr/xgen-ide/04_2024/15_data/result.csv") as f:
        reader = csv.reader(f)
        input_data = []
        for idx, row in enumerate(reader):
            # if idx < 2000:
            #     continue
            if idx == 2000:
                break
            if idx % args.upload_every == 0:
                print (idx)
                upload(input_data, queue_name, task_name)
                input_data = []
            id = row[0]
            transcript = row[1]
            questions = row[2::2]
            answers = row[3::2]
            assert len(questions) == len(answers)
            input_data.append(
                (id, transcript, questions, answers)
            )
    if len(input_data) > 0:
        upload(input_data, queue_name, task_name)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--upload_every", type=int, default=-1)
    args = parser.parse_args()
    main(args)
